{% set version = "1.9.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-haplo.stats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/haplo.stats_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/haplo.stats/haplo.stats_{{ version }}.tar.gz
  sha256: 2fb73ecf99c0df282d8576b0e0a919b61f0d18befd069857b2e538075b33d9c0

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-arsenal                    # [build_platform != target_platform]
    - r-rms                        # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-arsenal
    - r-rms
  run:
    - r-base
    - r-arsenal
    - r-rms

test:
  commands:
    - $R -e "library('haplo.stats')"  # [not win]
    - "\"%R%\" -e \"library('haplo.stats')\""  # [win]

about:
  home: https://analytictools.mayo.edu/research/haplo-stats/
  dev_url: https://github.com/cran/haplo.stats
  license: GPL-2.0-or-later
  summary: Routines for the analysis of indirectly measured haplotypes. The statistical methods assume that all subjects are unrelated and that haplotypes are ambiguous (due to unknown linkage phase of the genetic markers). The main functions are
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
