travis:
  secure:
    BINSTAR_TOKEN: KhBpjAR3L/73miWn8nysBq3bBczfj8JZo9eOlbFcl79JH52QFFAA0AtcupHNVr2gKmwscn0SoevMRttzpxyXqxYEvZGFApfAi5NbKveNP5NnVo96DIofj+O/aHpl8Ze1IO69lv4mgSp9uosVPTy7xnbz0vUJt1CbuvhsNJf7YWur2ZFlHxqLFsZE1gEW3hNwmRdVCrIEo1942l8GTQzI6CYoN8vaLy3EyEyjs3Oy5Y7U3h6b5dqk169gJtA0czRRexlU6LkbdgYhMm2tUDGSoWaodGs1FdLniTKNiKve3mWcTVf+un8LFMWVya2e1RbPl88lipgv2q6MYAOd9IcLgFCKUVVKt44cJ5cdEso5qxNu0dA+5YzjfbBwu08OClF9PQv/49Ob4A2ENNkB5afIBkvI1fOuhzF01bIpji/v9VSjmFE3hJHH3sV58k56QCVN/FMgpHgaHaGuGWv3/6c/9CN+7kBjDlYJszTfTtbVTKUAwD3WsCqre7WNtLXMAKG/2SBABweb74VsAHsc06GC+2MtduQYEKo8sSon3U/Le7aTAFl4cvca44oGWUAxBWNgu8/wG102cb2Uawb06N7glHEPINoXtSgrxbT4TIRBlhYQqAqe3/S1SASuxdOV45lDuMOV/CN8KGDc9OQt0CYeAAAGiJNlCM1yUdbBgMCpi2M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
