travis:
  secure:
    BINSTAR_TOKEN: HIDnpU+6VY/Os4fFQEJEY2/DOWXLgMeqs44+AT8nXTE+G95mmJ+mD5r4KrZHm+nGLv1TbXGKBts5cBJEOLyh88OtbcuriMkScugCRiEdTggxpBLUsHGh590pUq4a2Sit66A7nQV9hnKfKEOX7CsRcaWQbtsLNT6l+JWEE5j1le4bXbK3fXopFQs0OtlTPNEwKiztfas1y6yAy0nOr4VeTj6lsTzboJkqG+qIsIQKS/d9wAdC9gB1vCYUNRn1sQbq3WoKBw5pOJSMdqEU8w6+8PLvc6NsDAAiDUodVYP1MD2SELaNV61DISDPidZ4iXJTNBsHRodQqC6FWbW/pOR3y9FY4jAjuQdPO0SjcUz/4oMbHpZDxjl8zPeziYVd/vbLpzQZGe1mwQRC7sLMN3ltcb4AWsh1J7Zt2BVt9xq5BuJa6TRwrVgq1b2p1RMqfAus/m3EhEo5n0GW7XzOwc3O1u7ND9IOGJ/ZWl5ieb6i/s22J027IcYBjEYt2dmj4tm/Mn3o0aC/4jc8ZmkbetR9O+/vnwGFJqdtdrh2ZsAaZCK5IbEh6l0RqI1lkONwP6byNaE3h+BausKypnIOTj07VcM7vayJTz8nmCm0UhZbcau0KmvR0r/b9cdoeEZbFVaHmiubIskT6CfkzBRraJE2MkzcnKRDh90Ng70EPMJMcxg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
