travis:
  secure:
    BINSTAR_TOKEN: QUWrsGHOoTv3DJncxKCVcAGk4N0uGqJ5ZdgvyFN9vy1lgpd0pmQv0Ba3SEELFKf0SWjFTme0byvYv5OK29WLZ6pEw332hQgDEu7kvDCZGSh4BqybEok11oR3rL4nDHLtGXOkq2jh2Yah5NlJ8lo6scg1HJLQcGsCq3D89xFrDkDWArw1UbdRQsGKCJkIisdd9nciUru36gEFu94yLGxarpt3AEDfF3h3bg7zRvQEAietPkzgKPe1JIYa152LktqOztBpxz3g3CyDU9a4l0na/qcsTLE8yLflpo5aozFeyptn+MXzXDP41Lf5n2z/4vmjD4f0egzuvtLRZe1ErEZv40pDgCd+tvASe4C5Lo8wa4vcxMUsOhBr4UABB6aY/qSewgraeIhS5+YBqigB9CUwmneTmhaPDSYs06ORKJ6Z0f2JJQjme1JjxSgo1yKVd9LK/MpbQ5YuclxWLReYoFVPtRWghEeJU5iMBpTigxFOauon6qL5h+6n/J4AwCJglxAujGl/7TMaqnPwbLmVoe5buJNCFM/UHe+0teiQ4NWU3y+nm+97s/vtqalObw9U0imu4SAtBU6BmcZGLT7DVCVJOJ5TSrREL9cmjZkc5/3kBigJbOm1hIBBH4XNgzkAH6C4XJ9BQOakUxhXiQU84GtjlfJKQLBFpCLMXSOaUgBqZ2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
