travis:
  secure:
    BINSTAR_TOKEN: BCClXDd4s6vETp0kVMST0pVRsqaZe12sfg0K3tX9buscKx2QcQm99FR0p9Kjz4+Io6JpvBpxILo86aQ8eHmh8CgwCWxhnQbZB04uThVidnXS1rdGdJNYPU/d1TCHrkfQIqXBVSgwMK7wIInCN4CD9cvGqnL73HxE+/672jebZJnTqzXpCr6spQ9rePWb7QIsFqUO9jpXCGAgcNZhWhkiPeHCuuyuNiid70kgoMjU06uhYubVb5u3/3I0jk5BTxTLsAkfyLtz73GGQWSV/z2lOu/cUNk+htbDaVh9QPHIc9Pfn1DtDna+7rfpUM07MB1YkEdBCGQ8Tmr7FGFWRjOnQndPEjf4wUymq1zDZGdcKkXQMzulExRyoPkkANNPr1LT1hICGrP/CyXcl3uzZZASzWMQaeyXw+hlJRmFlBls8lv/GrowmWwdlVmYk4UxwEiNg507p8o/gVkOx7gc/1/SgK60j55m8/eE/+6xSPYhHj4+uH1GYjTAy3wZ4tTvcIo43J2WZPSf/vWxpit7svZ4hU1npiNchboH7kngCf1eRCXjo+zuAFtGvTaHwR2wBp4v4rK4/j6Iyi0YrDJZINlYSuw5j/8bUb7pFVV0I5iKhg4CHpqJKqGJ6tjubnMjxH4GtyPzEJDcvg0ULU3aLM07o+b55sLK8ILNZ9HSvaZtDs8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
